apiVersion: apps/v1
kind: Deployment
metadata:
  name: tangerine-deployment
spec:
  selector:
    matchLabels:
      app: tangerine-app
  replicas: 2
  template:
    metadata:
      labels:
        app: tangerine-app
    spec:
      containers:
      - name: tangerine-app
        image: sardan5/tangerine:0.1.19
        ports:
        - containerPort: 4200
        
